--- # devspaces.yml
name: ravendbDev
description:  Development environment for RavenDB

# If you want to use a different Dockerfile for your DevSpace, provide the path
# here.
docker-file: Dockerfile

# If you need additional files when building your Dockerfile, such as some
# application binaries that your Dockerfile references, list the glob paths to
# include here. They are relative to this devspaces.yml file.
docker-build-includes: |
  **/*

ports:
- protocol: http # can be udp|tcp|http
  port-number: 8080
  description: web app http port
- protocol: tcp # can be udp|tcp|http
  port-number: 38888
  description: ravendb client port

sync-ignore: |
  .idea
  **/node_modules
  **/target

  [Bb]in
  [Oo]bj
  *resharper.user
  build/
  [Hh]elp/
  *.suo
  *.js.map
  *.less.map
  *.css.map
  *.sln.cache
  _ReSharper.*/
  *.user
  /artifacts
  /Data
  *.InstallLog
