#!/usr/bin/env bash

displayUsage() {
      cat $BASEDIR/docker-cli.hlp 2>/dev/null || true
}

BASEDIR=$(dirname $(readlink -f $0))
COMMAND="$1"

pushd $BASEDIR

case `awk '{print tolower($0)}' <<< "$COMMAND"` in
	start)
		mkdir -p scripts
		cp -f $BASEDIR/../install*.sh scripts
        docker-compose -f $BASEDIR/docker-compose.yml up --build -d
		rm -rf $BASEDIR/scripts
	;;
	build)
		mkdir -p scripts
		cp $BASEDIR/../install*.sh scripts
		docker-compose -f $BASEDIR/docker-compose.yml build
		rm -rf $BASEDIR/scripts
	;;
	up)
		docker-compose -f $BASEDIR/docker-compose.yml up -d
	;;
	exec)
		docker-compose -f $BASEDIR/docker-compose.yml exec ravendb-dev bash
	;;
	down)
		docker-compose -f $BASEDIR/docker-compose.yml down
	;;	
	stop)
		docker-compose -f $BASEDIR/docker-compose.yml stop
	;;
	*) displayUsage; exit 139
	;;
esac
