version: '2'

services:
  ravendb-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ravendb-dev
    ports:
      - 8080
      - 38888
      - 5005
    volumes:
      - ..:/data:Z
    command: bash
    tty: true
